kind: Service
apiVersion: v1
metadata:
  name: national-parks-lb
spec:
  selector:
    habitat-name: national-parks-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
